name: CI
on: [push]
jobs:
  lhci:
    name: Run Lighthouse CI on Shopify theme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run Lighthouse CI on Shopify theme
        uses:  Shopify/lighthouse-ci-action@v1.2.0
        with:
          store: ${{ secrets.SHOP_STORE_OS2 }}
          password: ${{ secrets.SHOP_PASSWORD_OS2 }}
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          collection_handle: all
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_TOKEN }}
          pull_theme: ${{ secrets.SHOP_PULL_THEME }}
  theme-check:
    name: Run Theme Check on Shopify theme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run Theme Check on Shopify theme
        uses: Shopify/theme-check-action@v1.3.0
        with:
          token: ${{ github.token }}
